version = 1

test_patterns = ["src/**"]

exclude_patterns = ["*/tests/**"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
  style_guide = "standard"
  environment = [
    "nodejs",
    "jest"
  ]